### ISSUE TITLE
Odd package.json errors 

### ISSUE THREAD

**Issue by owengriffin** [JanMalch/sveltekit-smelte-setup#2]
Hi, 

I get the following error when running `svelte-kit dev`:

```
$ ./node_modules/.bin/svelte-kit dev --port 3001 --host

  SvelteKit v1.0.0-next.112

  local:   http://localhost:3001
  network: http://192.168.0.100:3001


21:00:58 [vite] new dependencies found: smelte/src/components/Button, updating...
/sveltekit-smelte-setup/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/sveltekit-smelte-setup/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
21:00:58 [vite] error while updating dependencies:
Error: The service was stopped
    at /sveltekit-smelte-setup/node_modules/esbuild/lib/main.js:1209:25
    at /sveltekit-smelte-setup/node_modules/esbuild/lib/main.js:606:9
    at Socket.afterClose (/sveltekit-smelte-setup/node_modules/esbuild/lib/main.js:584:7)
    at Socket.emit (node:events:377:35)
    at Socket.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
````

```
$ npm -v
7.13.0
```

Removing the `package-lock.json` and doing an `npm install` gives esbuild errors:

```
> Build failed with 13 errors:
node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:524:10: error: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:525:16: error: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:526:15: error: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:548:10: error: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:548:32: error: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
...
```

**Comment by JanMalch** [comment]
I get the same `Big integer literals` errors with a fresh setup. You should create an issue at [svelte-add](https://github.com/svelte-add/svelte-add) or [tailwindcss](https://github.com/tailwindlabs/tailwindcss).

**Comment by JoshQuaintance** [comment]
Hello, I'm also getting this error, but only on a fresh setup for smelt

**Comment by martinjms** [comment]
I was also having this issue, I was able to solve it by adding "es2020" to vite's target as recommended in https://github.com/sveltejs/kit/issues/859

**Comment by JoshQuaintance** [comment]
@martinjms  Well now I'm having import problems

```
node_modules/purgecss/lib/purgecss.esm.js:1:78: error: No matching export in "browser-external:fs" for import "access"
node_modules/purgecss/lib/purgecss.esm.js:1:90: error: No matching export in "browser-external:fs" for import "readFile"
node_modules/purgecss/lib/purgecss.esm.js:1:104: error: No matching export in "browser-external:fs" for import "constants"
node_modules/purgecss/lib/purgecss.esm.js:1:135: error: No matching export in "browser-external:util" for import "promisify"
node_modules/rollup-pluginutils/dist/pluginutils.es.js:1:15: error: No matching export in "browser-external:path" for import "extname"
```
